name: serverrts
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf:
  shelf_web_socket:
  mongo_dart:
  uuid:
  bcrypt:
  crypto:
  dart_jsonwebtoken:
  equatable: ^2.0.5
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
